---
swagger: "2.0"
info:
  version: "2018-11-14T23:13:21Z"
  title: "syntinel"
host: "iveplpzxtk.execute-api.us-east-1.amazonaws.com"
basePath: "/syntinel-poc"
schemes:
- "https"
paths:
  /cue:
    post:
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "text/html"
      responses:
        200:
          description: "200 response"
          headers:
            Content-Type:
              type: "string"
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:121808128646:function:MyTestCueReceiverLambda/invocations"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Content-Type: "'text/html'"
            responseTemplates:
              text/html: "$input.path('$')"
        requestTemplates:
          application/x-www-form-urlencoded: "{\n    \"body\": \"$input.body\"\n}"
        passthroughBehavior: "when_no_templates"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws"
  /notify:
    post:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "SyntinelNotification"
        required: true
        schema:
          $ref: "#/definitions/SyntinelNotification"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
      x-amazon-apigateway-request-validator: "Validate body"
      x-amazon-apigateway-integration:
        credentials: "arn:aws:iam::121808128646:role/syntinel-lambda-role"
        uri: "arn:aws:apigateway:us-east-1:sqs:path//121808128646/syntinel-notifications"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.querystring.MessageBody: "method.request.body"
          integration.request.querystring.Version: "'2012-11-05'"
          integration.request.querystring.Action: "'SendMessage'"
          integration.request.header.Content-Type: "'applicaiton/json'"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
  SyntinelNotification:
    type: "object"
    required:
    - "Cues"
    - "Description"
    - "Name"
    - "Signal"
    properties:
      Name:
        type: "string"
      Description:
        type: "string"
      AllowMultiple:
        type: "boolean"
      Signal:
        type: "object"
        properties:
          ReporterId:
            type: "integer"
          Type:
            type: "string"
          Group:
            type: "string"
          Id:
            type: "string"
      Cues:
        type: "array"
        items:
          type: "object"
          properties:
            Id:
              type: "integer"
            Name:
              type: "string"
            Description:
              type: "string"
            Resolver:
              type: "object"
              properties:
                Type:
                  type: "string"
                Action:
                  type: "string"
                Variables:
                  type: "array"
                  items:
                    type: "object"
                    properties:
                      Name:
                        type: "string"
                      Type:
                        type: "string"
                      DefaultValue:
                        type: "string"
                      Options:
                        type: "array"
                    required:
                    - "Name"
                    - "Type"
              required:
              - "Type"
          required:
          - "Description"
          - "Id"
          - "Name"
          - "Resolver"
      DefaultCue:
        type: "integer"
      DefaultCueTimeout:
        type: "integer"
x-amazon-apigateway-request-validators:
  Validate body:
    validateRequestParameters: false
    validateRequestBody: true
