openapi: "3.0.1"
info:
  title: "syntinel"
  version: "2018-11-14T23:13:21Z"
servers:
- url: "https://iveplpzxtk.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/syntinel-poc"
paths:
  /cue:
    post:
      responses:
        200:
          description: "200 response"
          headers:
            Content-Type:
              schema:
                type: "string"
          content: {}
  /notify:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SyntinelNotification"
        required: true
      responses:
        200:
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
    SyntinelNotification:
      required:
      - "Cues"
      - "Description"
      - "Name"
      - "Signal"
      type: "object"
      properties:
        Name:
          type: "string"
        Description:
          type: "string"
        AllowMultiple:
          type: "boolean"
        Signal:
          type: "object"
          properties:
            ReporterId:
              type: "integer"
            Type:
              type: "string"
            Group:
              type: "string"
            Id:
              type: "string"
        Cues:
          type: "array"
          items:
            required:
            - "Description"
            - "Id"
            - "Name"
            - "Resolver"
            type: "object"
            properties:
              Id:
                type: "integer"
              Name:
                type: "string"
              Description:
                type: "string"
              Resolver:
                required:
                - "Type"
                type: "object"
                properties:
                  Type:
                    type: "string"
                  Action:
                    type: "string"
                  Variables:
                    type: "array"
                    items:
                      required:
                      - "Name"
                      - "Type"
                      type: "object"
                      properties:
                        Name:
                          type: "string"
                        Type:
                          type: "string"
                        DefaultValue:
                          type: "string"
                        Options:
                          type: "array"
        DefaultCue:
          type: "integer"
        DefaultCueTimeout:
          type: "integer"
